### ISSUE TITLE
Improve daily summary graphic

### ISSUE THREAD

**Issue by mankoff** [GEUS-Glaciology-and-Climate/mass_balance#27]
This graphic is better. 

https://twitter.com/matthias_huss/status/1677221547474386946

**Comment by mankoff** [comment]
Also, maybe just post on a website (PROMIChttps://twitter.com/matthias_huss/status/16772E? Polar Portal?) and not on Twitter...

**Comment by mankoff** [comment]
Daily graphic failing as of 18 July 2023.

```python
Traceback (most recent call last):
  File "./twitbot.py", line 113, in <module>
    api.update_status(tweet_str, media_ids=[media.media_id])
  File "/home/kdm/local/miniconda3/envs/TMB/lib/python3.8/site-packages/tweepy/api.py", line 205, in update_status
    return bind_api(
  File "/home/kdm/local/miniconda3/envs/TMB/lib/python3.8/site-packages/tweepy/binder.py", line 253, in _call
    return method.execute()
  File "/home/kdm/local/miniconda3/envs/TMB/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'message': 'You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product', 'code': 453}]
make[1]: *** [dist] Error 1
make: *** [update] Error 2
```

**Comment by mankoff** [comment]
People can make their own graphic pretty easily, especially if we solve #26
